import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";
import { prisma } from "@/lib/prisma";

const MOCK_USERS = [
  { name: "Sarah Connor", avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop" },
  { name: "Alex Mercer", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop" },
  { name: "Elena Fisher", avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop" },
  { name: "David Bowman", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop" },
  { name: "Aria Sterling", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop" }
];

const MOCK_COMMENTS = [
  { text: "This is exactly the tool I've been waiting for! The AI copywriter is clean. 🔥", sentiment: "POSITIVE" },
  { text: "Very smooth interface, but does it support threads or reels scheduling?", sentiment: "NEUTRAL" },
  { text: "I tried scheduling a video and it failed on my side. Any idea why?", sentiment: "NEGATIVE" },
  { text: "Loving the clean SVG dashboard layouts. Pixel-perfect! 🚀", sentiment: "POSITIVE" },
  { text: "Any plans to support Twitter/X or Facebook posting soon?", sentiment: "NEUTRAL" },
  { text: "Stunning graphics generated by Imagen. Looks very premium.", sentiment: "POSITIVE" }
];

export async function GET(req: NextRequest) {
  // Session check
  const session = await getServerSession(authOptions);
  const userId = session?.user?.id || "local-dev-user-id";

  try {
    // 1. Fetch connected accounts
    const accounts = await prisma.account.findMany({
      where: { userId },
    });

    // 2. Fetch post history (scheduled, published, failed)
    const posts = await prisma.post.findMany({
      where: { userId },
      include: { 
        media: true, 
        publishJobs: true,
        analytics: { orderBy: { recordedAt: "desc" }, take: 1 }, // Take the latest analytics log
        comments: { orderBy: { createdAt: "desc" } }
      },
      orderBy: { scheduledAt: "asc" },
    });

    // 3. Simulation Engine runner:
    const publishedPosts = posts.filter(p => p.status === "PUBLISHED");
    
    // Simulate background activity if published posts exist
    if (publishedPosts.length > 0) {
      // 40% chance of generating a new user comment event
      if (Math.random() < 0.4) {
        const targetPost = publishedPosts[Math.floor(Math.random() * publishedPosts.length)];
        const mockUser = MOCK_USERS[Math.floor(Math.random() * MOCK_USERS.length)];
        const mockComment = MOCK_COMMENTS[Math.floor(Math.random() * MOCK_COMMENTS.length)];

        // Save mock comment to DB
        await prisma.comment.create({
          data: {
            postId: targetPost.id,
            authorName: mockUser.name,
            authorAvatar: mockUser.avatar,
            text: mockComment.text,
            sentiment: mockComment.sentiment,
            isAdmin: false
          }
        });

        // Insert notification
        await prisma.notification.create({
          data: {
            userId,
            title: "New Engagement Event",
            message: `${mockUser.name} commented: "${mockComment.text.substring(0, 45)}..."`,
            type: "ENGAGEMENT"
          }
        });
      }

      // Simulate metric updates (impressions, likes, shares) for all published posts on load
      for (const post of publishedPosts) {
        const postPlatforms = JSON.parse(post.platforms) as string[];
        for (const plat of postPlatforms) {
          const lastAnalytic = await prisma.analytics.findFirst({
            where: { postId: post.id, platform: plat },
            orderBy: { recordedAt: "desc" }
          });

          const currentCommentsCount = await prisma.comment.count({ where: { postId: post.id } });

          await prisma.analytics.create({
            data: {
              postId: post.id,
              platform: plat,
              impressions: (lastAnalytic?.impressions || 120) + Math.floor(Math.random() * 20) + 5,
              likes: (lastAnalytic?.likes || 10) + Math.floor(Math.random() * 5) + 1,
              comments: currentCommentsCount,
              shares: (lastAnalytic?.shares || 2) + Math.floor(Math.random() * 2),
              clicks: (lastAnalytic?.clicks || 5) + Math.floor(Math.random() * 3),
              saves: (lastAnalytic?.saves || 3) + Math.floor(Math.random() * 2)
            }
          });
        }
      }
    }

    // 4. Re-fetch posts & analytics after running the simulation updates
    const refreshedPosts = await prisma.post.findMany({
      where: { userId },
      include: { 
        media: true, 
        publishJobs: true,
        analytics: { orderBy: { recordedAt: "desc" } }, // get all history logs for SVG charts
        comments: { orderBy: { createdAt: "desc" } }
      },
      orderBy: { scheduledAt: "asc" },
    });

    const parsedPosts = refreshedPosts.map((post) => ({
      ...post,
      platforms: JSON.parse(post.platforms) as string[],
    }));

    // Re-fetch analytics records
    const allAnalytics = await prisma.analytics.findMany({
      where: {
        post: { userId },
      },
      orderBy: { recordedAt: "desc" }
    });

    // Fetch Notifications
    const notifications = await prisma.notification.findMany({
      where: { userId },
      orderBy: { createdAt: "desc" },
      take: 12
    });

    const clientTasks = await prisma.clientTask.findMany({ where: { userId }, orderBy: { createdAt: "desc" } });
    const documents = await prisma.document.findMany({ where: { userId }, orderBy: { createdAt: "desc" } });
    const invoices = await prisma.invoice.findMany({ where: { userId }, orderBy: { createdAt: "desc" } });

    // If database has no posts or accounts, we return a hybrid payload with demo metrics
    if (refreshedPosts.length === 0 && accounts.length === 0) {
      console.log("[Dashboard API] Empty database detected. Returning premium sandbox mock details.");
      
      const demoAccounts = [
        {
          id: "demo-ig",
          provider: "instagram",
          platformUsername: "@socialforge_creator",
          platformDisplayName: "SocialForge Creator Page",
          platformAvatarUrl: null,
          createdAt: new Date(),
        },
        {
          id: "demo-li",
          provider: "linkedin",
          platformUsername: "socialforge-dashboard",
          platformDisplayName: "SocialForge official",
          platformAvatarUrl: null,
          createdAt: new Date(),
        },
        {
          id: "demo-tw",
          provider: "twitter",
          platformUsername: "@socialforge_io",
          platformDisplayName: "SocialForge IO",
          platformAvatarUrl: null,
          createdAt: new Date(),
        },
        {
          id: "demo-fb",
          provider: "facebook",
          platformUsername: "SocialForge Page",
          platformDisplayName: "SocialForge Page Profile",
          platformAvatarUrl: null,
          createdAt: new Date(),
        }
      ];

      const demoPosts = [
        {
          id: "demo-post-1",
          userId,
          caption: "AI-powered social media automation is the future. SocialForge allows you to build vertical Imagen 3 assets and schedule them globally. ✨",
          hashtags: "#marketing #artificialintelligence #future",
          scheduledAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000), // In 2 days
          publishedAt: null,
          status: "SCHEDULED",
          platforms: ["INSTAGRAM", "LINKEDIN"],
          errorLog: null,
          media: [
            {
              id: "demo-media-1",
              url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop",
              type: "IMAGE",
            },
          ],
          analytics: [],
          comments: []
        },
        {
          id: "demo-post-2",
          userId,
          caption: "Launching our brand new beta tools today! Try out the AI vertical asset creator. 🚀 #SaaS #buildinpublic",
          hashtags: "#buildinpublic #SaaS",
          scheduledAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
          publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
          status: "PUBLISHED",
          platforms: ["LINKEDIN", "TWITTER"],
          errorLog: null,
          media: [],
          analytics: [
            { id: "a1", postId: "demo-post-2", platform: "LINKEDIN", impressions: 1450, likes: 82, comments: 4, shares: 12, recordedAt: new Date(Date.now() - 12 * 60 * 60 * 1000) },
            { id: "a2", postId: "demo-post-2", platform: "TWITTER", impressions: 840, likes: 32, comments: 2, shares: 8, recordedAt: new Date(Date.now() - 12 * 60 * 60 * 1000) },
            { id: "a3", postId: "demo-post-2", platform: "LINKEDIN", impressions: 2100, likes: 110, comments: 6, shares: 18, recordedAt: new Date() },
            { id: "a4", postId: "demo-post-2", platform: "TWITTER", impressions: 1250, likes: 45, comments: 3, shares: 14, recordedAt: new Date() }
          ],
          comments: [
            { id: "c1", postId: "demo-post-2", authorName: "Sarah Connor", authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop", text: "This is exactly what I needed for my LinkedIn flow! Super clean UI. 🔥", sentiment: "POSITIVE", createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000), parentId: null, isAdmin: false },
            { id: "c2", postId: "demo-post-2", authorName: "Admin (You)", authorAvatar: null, text: "Thanks Sarah! Glad it's helping you streamline. Let us know if you have feedback.", sentiment: "NEUTRAL", createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000), parentId: "c1", isAdmin: true },
            { id: "c3", postId: "demo-post-2", authorName: "Alex Mercer", authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop", text: "Does this handle scheduling for threads too?", sentiment: "NEUTRAL", createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000), parentId: null, isAdmin: false }
          ]
        },
        {
          id: "demo-post-3",
          userId,
          caption: "This post failed to publish due to expired tokens. Re-authenticate accounts to fix. #marketing",
          hashtags: "#error",
          scheduledAt: new Date(Date.now() - 4 * 60 * 60 * 1000), // 4 hours ago
          publishedAt: null,
          status: "FAILED",
          platforms: ["INSTAGRAM"],
          errorLog: "[Instagram Error]: OAuth token expired (Session expired or invalidated by Meta).",
          media: [
            {
              id: "demo-media-2",
              url: "https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=800&auto=format&fit=crop",
              type: "IMAGE",
            },
          ],
          analytics: [],
          comments: []
        },
      ];

      const demoNotifications = [
        { id: "n1", userId, title: "Account Auto-Synced", message: "Instagram and LinkedIn sandbox channels verified successfully.", type: "SUCCESS", read: false, createdAt: new Date() },
        { id: "n2", userId, title: "New Engagement Event", message: "Sarah Connor liked and commented on your LinkedIn post.", type: "ENGAGEMENT", read: false, createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000) }
      ];

      const demoClientTasks = [
        { id: "t1", title: "Promo Video Q3", type: "VIDEO", status: "IN_PROGRESS" },
        { id: "t2", title: "Summer Campaign Poster", type: "POSTER", status: "TESTING" },
        { id: "t3", title: "Reels batch #4", type: "VIDEO", status: "PENDING" }
      ];
      
      const demoDocuments = [
        { id: "d1", title: "Brand Guidelines.pdf", url: "#", type: "PDF", size: 2048000, createdAt: new Date() }
      ];
      
      const demoInvoices = [
        { id: "i1", title: "June Social Media Mgmt", amount: 1500, status: "UNPAID", dueDate: new Date(Date.now() + 5*24*60*60*1000) },
        { id: "i2", title: "May Content Creation", amount: 1200, status: "PAID", dueDate: new Date(Date.now() - 15*24*60*60*1000) }
      ];

      return NextResponse.json({
        success: true,
        isDemo: true,
        accounts: demoAccounts,
        posts: demoPosts,
        notifications: demoNotifications,
        clientTasks: demoClientTasks,
        documents: demoDocuments,
        invoices: demoInvoices,
        metrics: {
          totalScheduled: 1,
          totalPublished: 1,
          totalFailed: 1,
          totalReach: 3350,
          engagementRate: "4.9%",
        },
      });
    }

    // Otherwise, compute real metrics from database
    const totalScheduled = parsedPosts.filter((p) => p.status === "SCHEDULED").length;
    const totalPublished = parsedPosts.filter((p) => p.status === "PUBLISHED").length;
    const totalFailed = parsedPosts.filter((p) => p.status === "FAILED").length;
    
    // Compute total impressions and engagements
    // Group analytics by post+platform to grab the latest record
    const latestAnalyticsMap = new Map<string, typeof allAnalytics[0]>();
    allAnalytics.forEach((item) => {
      const key = `${item.postId}-${item.platform}`;
      if (!latestAnalyticsMap.has(key)) {
        latestAnalyticsMap.set(key, item);
      }
    });

    const latestAnalytics = Array.from(latestAnalyticsMap.values());
    const totalImpressions = latestAnalytics.reduce((sum, item) => sum + item.impressions, 0);
    const totalLikes = latestAnalytics.reduce((sum, item) => sum + item.likes, 0);
    
    // Sum comments from Comment table
    const allComments = parsedPosts.flatMap(p => p.comments);
    const totalComments = allComments.length;
    const totalShares = latestAnalytics.reduce((sum, item) => sum + item.shares, 0);
    
    const engagements = totalLikes + totalComments + totalShares;
    const engagementRate = totalImpressions > 0 ? `${((engagements / totalImpressions) * 100).toFixed(1)}%` : "0.0%";

    return NextResponse.json({
      success: true,
      isDemo: false,
      accounts,
      posts: parsedPosts,
      notifications,
      clientTasks,
      documents,
      invoices,
      metrics: {
        totalScheduled,
        totalPublished,
        totalFailed,
        totalReach: totalImpressions || 150, // baseline
        engagementRate,
      },
    });
  } catch (error: any) {
    console.error("Dashboard Fetch API Error:", error);
    return NextResponse.json(
      { error: error.message || "Failed to load dashboard data." },
      { status: 500 }
    );
  }
}
